--CREATE STAGE
    
    
    -- CREATE FILE FORMAT 

    CREATE OR REPLACE FILE FORMAT YELP_WEATHER_INSIGHTS.STAGING.fileformat_gcp
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1;
   
   --CREATE JSON FORMAT
    CREATE OR REPLACE FILE FORMAT YELP_WEATHER_INSIGHTS.STAGING.JSONFORMAT
    TYPE = JSON;
    
    -- CREATE EXTERNAL STAGE OBJECT FOR CSV SOURCE
                                    --FILE
    CREATE OR REPLACE STAGE YELP_WEATHER_INSIGHTS.STAGING.stage_gcp
    STORAGE_INTEGRATION = gcp_integration
    URL = 'gcs://snowflackbucketgcps'
    FILE_FORMAT = fileformat_gcp;

    -- CREATE EXTERNAL STAGE OBJECT FOR JSON SOURCE
    CREATE OR REPLACE STAGE YELP_WEATHER_INSIGHTS.STAGING.JSONSTAGE
    STORAGE_INTEGRATION = gcp_integration
    URL = 'gcs://snowflakebucketgcpjsons'
    FILE_FORMAT =JSONFORMAT;
    


    
    
-- LIST FILES CONTAINED IN STAGE
LIST @YELP_WEATHER_INSIGHTS.STAGING.STAGE_GCP;
LIST @YELP_WEATHER_INSIGHTS.STAGING.JSONSTAGE;






    