-- SETUP

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS yelp_weather_insights;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ODS;
CREATE SCHEMA IF NOT EXISTS DWH;


ALTER WAREHOUSE COMPUTE_WH SET WAREHOUSE_SIZE = 'XSMALL'
